-- ============================================================
-- CASE STUDY: SWIGGY - SQL BUSINESS ANALYSIS
-- Database: SwiggyDB
-- Author: Deepak
-- Module: Swiggy Data Analysis
-- ============================================================

USE SwiggyDB;

-- Analyze the database schema by listing all tables and
-- counting the number of columns in each table.
SHOW Tables;
SELECT COUNT(*) 
FROM Information_Schema.Tables
WHERE Table_Schema = 'SwiggyDB';

-- ============================================================
-- Q1: Display all customers who live in 'Delhi'.
-- Business Problem:
-- Swiggy's marketing team wants to identify customers living
-- in Delhi for targeted marketing campaigns.
-- ============================================================

SELECT 
    customer_id, name, city
FROM
    customers
WHERE
    city = 'Delhi';

-- Insight:
-- Identifies customers eligible for Delhi-specific campaigns.

-- ============================================================
-- Q2: Find the average rating of all restaurants in 'Mumbai'.
-- Business Problem:
-- Swiggy wants to evaluate the overall customer satisfaction level
-- of restaurants in Mumbai by calculating their average rating.
-- ============================================================

SELECT 
    city, ROUND(AVG(rating), 1) AS average_rating
FROM
    restaurants
WHERE
    city = 'Mumbai'
GROUP BY city;

-- Insight:
-- The average rating helps identify the general service and food
-- quality standards of restaurants operating in Mumbai.

-- ============================================================
-- Q3: List all customers who have placed at least one order.
-- Business Problem:
-- Swiggy wants to identify active customers who have made at least
-- one purchase on the platform for customer engagement and retention analysis.
-- ============================================================

SELECT 
    c.customer_id, c.name
FROM
    customers AS c
WHERE
    EXISTS (SELECT 
					1
		FROM
            orders AS o
        WHERE
            o.customer_id = c.customer_id);
            
-- Insight:
-- These customers represent the active user base and can be targeted
-- for loyalty programs, personalized offers, and repeat-order campaigns.

-- ============================================================
-- Q4: Display the total number of orders placed by each customers.
-- Business Problem:
-- Swiggy wants to measure customer activity by determining how many
-- orders each customer has placed on the platform.
-- ============================================================

SELECT 
    c.name, c.customer_id, COUNT(o.order_id) AS total_order
FROM
    customers c
        LEFT JOIN
    orders o ON o.customer_id = c.customer_id
GROUP BY c.customer_id , c.name;

-- Insight:
-- Order frequency helps identify loyal customers, understand purchasing
-- behavior, and support customer segmentation strategies.

-- ============================================================
-- Q5: Find the total revenue generated by each restaurant.
-- Business Problem:
-- Swiggy wants to identify how much revenue each restaurant contributes
-- to the platform in order to evaluate business performance.
-- ============================================================

SELECT 
    r.restaurant_id, r.name,
    COALESCE(SUM(o.total_amount), 0) AS total_revenue
FROM
    restaurants AS r
        LEFT JOIN
    orders AS o ON r.restaurant_id = o.restaurant_id
        AND o.status = 'Completed'
GROUP BY r.restaurant_id, r.name
ORDER BY total_revenue DESC;

-- Insight:
-- Revenue analysis helps identify top-performing restaurants, support
-- partnership decisions, and prioritize high-value business relationships.

-- ============================================================
-- Q6: Find the top 5 restaurants with the highest average rating.
-- Business Problem:
-- Swiggy wants to identify the highest-rated restaurants to
-- understand customer preferences and highlight top-performing
-- restaurant partners on the platform.
-- ============================================================

SELECT 
    restaurant_id, ROUND(AVG(rating), 1) AS average_rating
FROM
    restaurants
GROUP BY restaurant_id
ORDER BY average_rating DESC
LIMIT 5;

-- Insight:
-- Top-rated restaurants indicate strong customer satisfaction
-- and can be prioritized for promotions, recommendations, and
-- strategic partnerships.

-- ============================================================
-- Q7: Display all customers who have never placed an order.
-- Business Problem:
-- Swiggy wants to identify registered customers who have never
-- placed an order in order to understand inactive users and
-- improve customer engagement.
-- ============================================================

SELECT 
    c.customer_id, c.name
FROM
    customers AS c
WHERE
	NOT EXISTS (SELECT 
					1
		FROM
            orders AS o
        WHERE
            o.customer_id = c.customer_id);
            
-- Insight:
-- These customers represent potential growth opportunities and
-- can be targeted with onboarding offers, discounts, and
-- re-engagement campaigns.

-- ============================================================
-- Q8: Find the number of orders placed by each customer in 'Mumbai'.
-- Business Problem:
-- Swiggy wants to analyze customer ordering activity in Mumbai
-- to understand local customer engagement and purchasing behavior.
-- ============================================================

SELECT 
    c.customer_id,
    c.name,
    c.city,
    COUNT(o.order_id) AS total_order
FROM
    customers c
        LEFT JOIN
    orders o ON c.customer_id = o.customer_id
WHERE
    c.city = 'Mumbai'
GROUP BY c.customer_id;

-- Insight:
-- Order counts help identify active customers in Mumbai and can
-- support targeted marketing, loyalty programs, and customer
-- retention strategies.

-- ============================================================
-- Q9: Display all orders placed in last 30 days.
-- Business Problem:
-- Swiggy wants to monitor recent customer activity by identifying
-- all orders placed within the last 30 days.
-- ============================================================

SELECT 
    order_id, order_date
FROM
    orders
WHERE
    order_date >= (SELECT 
            MAX(order_date) - INTERVAL 30 DAY
        FROM
            orders);
            
-- Insight:
-- Recent order data helps track current demand trends, customer
-- engagement levels, and short-term business performance.

 -- ============================================================
-- Q10: List all delivery partners who have completed more than 1 delivery.
-- Business Problem:
-- Swiggy wants to identify delivery partners who have handled
-- multiple deliveries in order to evaluate partner activity and
-- operational contribution.
 -- ============================================================
 
SELECT 
    *
FROM
    deliveryupdates;
SELECT 
    d.partner_id,
    d.name,
    COUNT(DISTINCT od.order_id) AS total_delivery
FROM
    deliverypartners AS d
        JOIN
    orderdelivery AS od ON d.partner_id = od.partner_id
        JOIN
    deliveryupdates AS du ON od.order_id = du.order_id
WHERE
    du.status = 'Delivered'
GROUP BY d.partner_id , d.name
HAVING total_delivery > 1;

-- Insight:
-- Delivery partners with higher delivery counts are key contributors
-- to the delivery network and may be considered for performance
-- recognition, incentives, or workload analysis.

 -- ============================================================
-- Q11: Find the customers who have placed orders on exactly three diffrent days.
-- Business Problem:
-- Swiggy wants to identify customers who order regularly but not
-- excessively by finding customers who have placed orders on exactly
-- three different days.
 -- ============================================================

SELECT 
    c.customer_id,
    c.name,
    COUNT(DISTINCT DATE(o.order_date)) AS unique_date
FROM
    customers AS c
        JOIN
    orders AS o ON c.customer_id = o.customer_id
GROUP BY c.customer_id , c.name
HAVING unique_date = 3;

-- Insight:
-- This analysis helps understand customer ordering patterns and can
-- be used to segment moderately active customers for targeted
-- engagement and retention campaigns.

 -- ============================================================
-- Q12: Find the delivery partners who has worked with the most diffrent customers.
-- Business Problem:
-- Swiggy wants to identify delivery partners who have served the
-- highest number of unique customers in order to evaluate partner
-- reach and customer coverage.
 -- ============================================================

SELECT 
    d.partner_id,
    d.name,
    COUNT(DISTINCT o.customer_id) AS unique_customers
FROM
    deliverypartners AS d
        JOIN
    orderdelivery AS od ON d.partner_id = od.partner_id
        JOIN
    orders AS o ON o.order_id = od.order_id
GROUP BY d.partner_id , d.name
ORDER BY unique_customers DESC
LIMIT 1;

-- Insight:
-- Delivery partners who work with a larger variety of customers
-- demonstrate broader service coverage and may be among the most
-- versatile and active members of the delivery network.

 -- ============================================================
-- Q13: Identify customers who have the same city and have placed orders at the same restaurant, but on diffrent dates.
-- Business Problem:
-- Swiggy wants to identify customers from the same city who prefer
-- the same restaurant but visit/order on different dates. This helps
-- understand shared customer preferences and ordering behavior within
-- a location.

SELECT DISTINCT
    c1.customer_id, c1.city, o.restaurant_id, DATE(o.order_date)
FROM
    customers AS c1
        JOIN
    orders AS o ON c1.customer_id = o.customer_id
        JOIN
    customers AS c2 ON c1.city = c2.city
        AND c1.customer_id < c2.customer_id
        JOIN
    orders AS o2 ON c2.customer_id = o2.customer_id
        AND o.restaurant_id = o2.restaurant_id
WHERE
    DATE(o.order_date) <> DATE(o2.order_date);


-- Insight:
-- Customers from the same city ordering from the same restaurant on
-- different dates may indicate consistent restaurant popularity and
-- recurring demand among local customer groups.


